# Generated by Django 4.1.7 on 2023-03-18 13:12

import ckeditor.fields
from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=50)),
                ('text', models.TextField(max_length=300)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contact',
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('image', django_resized.forms.ResizedImageField(crop=None, force_format='WebP', keep_meta=True, quality=75, scale=0.5, size=[640, None], upload_to='attraction_images')),
                ('text', ckeditor.fields.RichTextField()),
                ('slug', models.SlugField(blank=True, max_length=100, null=True)),
                ('featured', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Service Category',
                'verbose_name_plural': 'Service Categories',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=30)),
                ('firstname', models.CharField(max_length=30)),
                ('image', django_resized.forms.ResizedImageField(crop=None, force_format='WebP', keep_meta=True, quality=75, scale=0.5, size=[640, None], upload_to='team_images')),
                ('phone', models.CharField(blank=True, max_length=100, null=True)),
                ('job', models.CharField(blank=True, max_length=100, null=True)),
                ('text', ckeditor.fields.RichTextField()),
                ('hierarchy', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Team Member',
                'verbose_name_plural': 'Team Members',
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=30)),
                ('lname', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('thumbnail', django_resized.forms.ResizedImageField(crop=None, force_format='WebP', keep_meta=True, quality=75, scale=0.5, size=[640, None], upload_to='testimonial_images')),
                ('text', ckeditor.fields.RichTextField(max_length=300)),
                ('status', models.BooleanField(default='False')),
            ],
            options={
                'verbose_name': 'Testimonial',
                'verbose_name_plural': 'Testimonials',
            },
        ),
    ]
