# Generated by Django 3.2.22 on 2023-10-17 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='categ',
            field=models.CharField(choices=[('past', 'past'), ('future', 'future')], default='past', max_length=50),
            preserve_default=False,
        ),
    ]
