# Generated by Django 3.2.22 on 2023-10-17 20:34

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_event_categ'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='text_en',
            field=ckeditor.fields.RichTextField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='text_ro',
            field=ckeditor.fields.RichTextField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='title_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='title_ro',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='text_en',
            field=ckeditor.fields.RichTextField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='text_ro',
            field=ckeditor.fields.RichTextField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='title_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='title_ro',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='main_explanation_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='main_explanation_ro',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_ro',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='second_text_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='second_text_ro',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='subtitle_en',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='subtitle_ro',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='gallery',
            name='name_en',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='gallery',
            name='name_ro',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='gallery',
            name='text_en',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='gallery',
            name='text_ro',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='media',
            name='name_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='media',
            name='name_ro',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='text_en',
            field=ckeditor.fields.RichTextField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='text_ro',
            field=ckeditor.fields.RichTextField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_ro',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='name_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='name_ro',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='text_en',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='text_ro',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='name_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='name_ro',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='teaching',
            name='text_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='teaching',
            name='text_ro',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='teaching',
            name='title_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='teaching',
            name='title_ro',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='teamrole',
            name='title_en',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='teamrole',
            name='title_ro',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='trainer',
            name='experience_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='trainer',
            name='experience_ro',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='trainer',
            name='intro_en',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='trainer',
            name='intro_ro',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='trainer',
            name='job_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trainer',
            name='job_ro',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trainer',
            name='skill1_descr_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='trainer',
            name='skill1_descr_ro',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='trainer',
            name='skill1_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='trainer',
            name='skill1_ro',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='trainer',
            name='skill2_descr_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='trainer',
            name='skill2_descr_ro',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='trainer',
            name='skill2_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='trainer',
            name='skill2_ro',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='trainer',
            name='skill3_descr_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='trainer',
            name='skill3_descr_ro',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='trainer',
            name='skill3_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='trainer',
            name='skill3_ro',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='trainer',
            name='text_en',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='trainer',
            name='text_ro',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
