# Generated by Django 4.1.7 on 2023-03-19 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_gallery_categ_service'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Contact', 'verbose_name_plural': 'Contacts'},
        ),
        migrations.AlterModelOptions(
            name='gallery',
            options={'verbose_name': 'Gallery', 'verbose_name_plural': 'Gallery'},
        ),
    ]
