# Generated by Django 4.1.7 on 2023-03-19 15:07

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_alter_contact_options_alter_gallery_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecategory',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, default='a', force_format='WebP', keep_meta=True, quality=75, scale=0.5, size=[640, None], upload_to='attraction_images'),
            preserve_default=False,
        ),
    ]
