# Generated by Django 4.1.7 on 2023-03-19 15:54

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_servicecategory_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='WebP', keep_meta=True, quality=75, scale=0.5, size=[640, None], upload_to='service_images'),
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='WebP', keep_meta=True, quality=75, scale=0.5, size=[640, None], upload_to='servicecategory_images'),
        ),
    ]
