# Generated by Django 4.1.7 on 2023-03-19 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_alter_service_image_alter_servicecategory_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Service',
        ),
    ]
