# Generated by Django 4.1.7 on 2023-03-19 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_delete_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='categ',
        ),
        migrations.DeleteModel(
            name='ServiceCategory',
        ),
    ]
