# Generated by Django 3.2.22 on 2023-10-18 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_auto_20231018_1159'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeekDays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=9)),
                ('slug', models.SlugField()),
            ],
            options={
                'verbose_name': 'Week Days',
                'verbose_name_plural': 'Week Days',
            },
        ),
        migrations.AlterField(
            model_name='trainingschedule',
            name='day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.weekdays'),
        ),
        migrations.AlterField(
            model_name='trainingschedule',
            name='day_en',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='services.weekdays'),
        ),
        migrations.AlterField(
            model_name='trainingschedule',
            name='day_ro',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='services.weekdays'),
        ),
    ]
