# Generated by Django 3.2.22 on 2023-10-18 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_auto_20231018_1159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingschedule',
            name='day_en',
        ),
        migrations.RemoveField(
            model_name='trainingschedule',
            name='day_ro',
        ),
    ]
