# Generated by Django 4.1.7 on 2023-03-19 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_service'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Team',
        ),
    ]
