# Generated by Django 3.2.22 on 2023-10-18 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_auto_20231018_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='weekdays',
            name='name_en',
            field=models.CharField(max_length=9, null=True),
        ),
        migrations.AddField(
            model_name='weekdays',
            name='name_ro',
            field=models.CharField(max_length=9, null=True),
        ),
        migrations.AddField(
            model_name='weekdays',
            name='slug_en',
            field=models.SlugField(null=True),
        ),
        migrations.AddField(
            model_name='weekdays',
            name='slug_ro',
            field=models.SlugField(null=True),
        ),
    ]
