# Generated by Django 4.1.7 on 2023-03-19 16:29

import ckeditor.fields
from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0010_delete_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=30)),
                ('firstname', models.CharField(max_length=30)),
                ('image', django_resized.forms.ResizedImageField(crop=None, force_format='WebP', keep_meta=True, quality=75, scale=0.5, size=[640, None], upload_to='team_images')),
                ('phone', models.CharField(blank=True, max_length=100, null=True)),
                ('job', models.CharField(blank=True, max_length=100, null=True)),
                ('job_ro', models.CharField(blank=True, max_length=100, null=True)),
                ('job_en', models.CharField(blank=True, max_length=100, null=True)),
                ('job_de', models.CharField(blank=True, max_length=100, null=True)),
                ('text', ckeditor.fields.RichTextField()),
                ('text_ro', ckeditor.fields.RichTextField(null=True)),
                ('text_en', ckeditor.fields.RichTextField(null=True)),
                ('text_de', ckeditor.fields.RichTextField(null=True)),
                ('hierarchy', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Team Member',
                'verbose_name_plural': 'Team Members',
            },
        ),
    ]
