# Generated by Django 3.2.22 on 2023-10-18 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0010_auto_20231018_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingschedule',
            name='training2_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trainingschedule',
            name='training2_ro',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trainingschedule',
            name='training3_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trainingschedule',
            name='training3_ro',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
