# Generated by Django 3.2.22 on 2023-10-18 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0011_auto_20231018_1224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingschedule',
            name='ending_time',
        ),
        migrations.RemoveField(
            model_name='trainingschedule',
            name='starting_time',
        ),
        migrations.AddField(
            model_name='trainingschedule',
            name='ending_time1',
            field=models.TimeField(blank=True, default='17:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trainingschedule',
            name='ending_time2',
            field=models.TimeField(blank=True, default='18:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trainingschedule',
            name='ending_time3',
            field=models.TimeField(blank=True, default='19:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trainingschedule',
            name='starting_time1',
            field=models.TimeField(blank=True, default='19:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trainingschedule',
            name='starting_time2',
            field=models.TimeField(blank=True, default='19:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trainingschedule',
            name='starting_time3',
            field=models.TimeField(blank=True, default='10:00'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trainingschedule',
            name='training1',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='trainingschedule',
            name='training1_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='trainingschedule',
            name='training1_ro',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='trainingschedule',
            name='training2',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='trainingschedule',
            name='training2_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='trainingschedule',
            name='training2_ro',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='trainingschedule',
            name='training3',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='trainingschedule',
            name='training3_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='trainingschedule',
            name='training3_ro',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
