# Generated by Django 3.2.18 on 2023-04-09 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0011_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecategory',
            name='rank',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
