# Generated by Django 3.2.22 on 2023-10-18 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0012_auto_20231018_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingschedule',
            name='ending_time1',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trainingschedule',
            name='ending_time2',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trainingschedule',
            name='ending_time3',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trainingschedule',
            name='starting_time1',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trainingschedule',
            name='starting_time2',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trainingschedule',
            name='starting_time3',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trainingschedule',
            name='training1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='trainingschedule',
            name='training2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='trainingschedule',
            name='training3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
