# Generated by Django 3.2.22 on 2023-10-18 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0013_auto_20231018_1231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weekdays',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='weekdays',
            name='slug_en',
        ),
        migrations.RemoveField(
            model_name='weekdays',
            name='slug_ro',
        ),
    ]
