# Generated by Django 3.2.22 on 2023-10-18 19:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0015_alter_testimonial_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
