# Generated by Django 3.2.18 on 2023-04-28 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0016_subscriber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testimonial',
            name='thumbnail',
        ),
    ]
