# Generated by Django 3.2.18 on 2023-04-28 20:29

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0017_remove_testimonial_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='text',
            field=ckeditor.fields.RichTextField(max_length=400),
        ),
    ]
