# Generated by Django 3.2.22 on 2023-11-05 19:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0018_results_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 5, 19, 51, 25, 622181, tzinfo=utc)),
        ),
    ]
