# Generated by Django 3.2.18 on 2023-04-28 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0018_alter_testimonial_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='hierarchy',
            new_name='role',
        ),
    ]
