# Generated by Django 3.2.18 on 2023-04-28 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0020_auto_20230428_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='role',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='services.teamrole'),
            preserve_default=False,
        ),
    ]
