# Generated by Django 3.2.18 on 2023-04-28 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0021_team_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='slug',
            field=models.SlugField(default='a'),
            preserve_default=False,
        ),
    ]
