# Generated by Django 3.2.22 on 2023-11-25 16:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0022_alter_contact_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='categ',
        ),
        migrations.AlterField(
            model_name='contact',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 25, 16, 21, 49, 801784, tzinfo=utc)),
        ),
    ]
