# Generated by Django 3.2.18 on 2023-04-28 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0022_team_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='intro',
            field=models.CharField(default='a', max_length=500),
            preserve_default=False,
        ),
    ]
