# Generated by Django 3.2.18 on 2023-04-28 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0023_team_intro'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='competitions',
            field=models.IntegerField(default=90),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='email',
            field=models.EmailField(default='catalinpetre25@gmail.com', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='experience',
            field=models.TextField(default='a'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='nr_students',
            field=models.IntegerField(default=45),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='skill1',
            field=models.CharField(default='a', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='skill1_descr',
            field=models.TextField(default='a'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='skill1_level',
            field=models.IntegerField(default=90),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='skill2',
            field=models.CharField(default='a', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='skill2_descr',
            field=models.TextField(default='a'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='skill2_level',
            field=models.IntegerField(default=89),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='skill3',
            field=models.CharField(default='a', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='skill3_descr',
            field=models.TextField(default='a'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='skill3_level',
            field=models.IntegerField(default=87),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='training_hours',
            field=models.IntegerField(default=1890),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='team',
            name='phone',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
