# Generated by Django 3.2.18 on 2023-04-30 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0026_training'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
