# Generated by Django 3.2.18 on 2023-04-30 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0027_training_active'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Team',
            new_name='Trainer',
        ),
        migrations.AlterModelOptions(
            name='trainer',
            options={'verbose_name': 'Trainer', 'verbose_name_plural': 'Trainers'},
        ),
    ]
