# Generated by Django 3.2.18 on 2023-04-30 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0028_auto_20230430_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='text_de',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='training',
            name='text_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='training',
            name='text_ro',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='training',
            name='title_de',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='training',
            name='title_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='training',
            name='title_ro',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
