# Generated by Django 3.2.18 on 2023-04-30 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0029_auto_20230430_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamrole',
            name='title_de',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='teamrole',
            name='title_en',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='teamrole',
            name='title_ro',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
