# Generated by Django 3.2.18 on 2023-04-30 11:56

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0030_auto_20230430_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, default='a', force_format='WebP', keep_meta=True, quality=75, scale=0.5, size=[640, None], upload_to='training_types_images'),
            preserve_default=False,
        ),
    ]
