# Generated by Django 3.2.18 on 2023-04-30 12:38

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0032_training_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_text', models.EmailField(max_length=200)),
                ('what_we_teach1', models.CharField(max_length=30)),
                ('what_we_teach2', models.CharField(max_length=30)),
                ('what_we_teach3', models.CharField(max_length=30)),
                ('what_we_teach4', models.CharField(max_length=30)),
                ('about_image', django_resized.forms.ResizedImageField(crop=None, force_format='WebP', keep_meta=True, quality=75, scale=0.5, size=[1500, None], upload_to='about_images')),
                ('founder_image', django_resized.forms.ResizedImageField(crop=None, force_format='WebP', keep_meta=True, quality=75, scale=0.5, size=[640, None], upload_to='founder_images')),
                ('emphasize_what_we_teach1', models.CharField(max_length=200)),
                ('emphasize_what_we_teach_icon1', django_resized.forms.ResizedImageField(crop=None, force_format='WebP', keep_meta=True, quality=75, scale=0.5, size=[1500, None], upload_to='about_icons')),
                ('emphasize_what_we_teach2', models.CharField(max_length=200)),
                ('emphasize_what_we_teach_icon2', django_resized.forms.ResizedImageField(crop=None, force_format='WebP', keep_meta=True, quality=75, scale=0.5, size=[1500, None], upload_to='about_icons')),
                ('emphasize_what_we_teach3', models.CharField(max_length=200)),
                ('emphasize_what_we_teach_icon3', django_resized.forms.ResizedImageField(crop=None, force_format='WebP', keep_meta=True, quality=75, scale=0.5, size=[1500, None], upload_to='about_icons')),
                ('emphasize_what_we_teach4', models.CharField(max_length=200)),
                ('emphasize_what_we_teach_icon4', django_resized.forms.ResizedImageField(crop=None, force_format='WebP', keep_meta=True, quality=75, scale=0.5, size=[1500, None], upload_to='about_icons')),
                ('video_link', models.CharField(max_length=300)),
                ('counter_fact1', models.IntegerField()),
                ('counter_fact2', models.IntegerField()),
                ('counter_fact3', models.IntegerField()),
                ('counter_fact4', models.IntegerField()),
            ],
        ),
    ]
