# Generated by Django 3.2.18 on 2023-04-30 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0033_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='counter_fact1_de',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='counter_fact1_en',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='counter_fact1_ro',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='counter_fact2_de',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='counter_fact2_en',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='counter_fact2_ro',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='counter_fact3_de',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='counter_fact3_en',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='counter_fact3_ro',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='counter_fact4_de',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='counter_fact4_en',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='counter_fact4_ro',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='emphasize_what_we_teach1_de',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='emphasize_what_we_teach1_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='emphasize_what_we_teach1_ro',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='emphasize_what_we_teach2_de',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='emphasize_what_we_teach2_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='emphasize_what_we_teach2_ro',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='emphasize_what_we_teach3_de',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='emphasize_what_we_teach3_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='emphasize_what_we_teach3_ro',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='emphasize_what_we_teach4_de',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='emphasize_what_we_teach4_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='emphasize_what_we_teach4_ro',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='main_text_de',
            field=models.EmailField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='main_text_en',
            field=models.EmailField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='main_text_ro',
            field=models.EmailField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='what_we_teach1_de',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='what_we_teach1_en',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='what_we_teach1_ro',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='what_we_teach2_de',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='what_we_teach2_en',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='what_we_teach2_ro',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='what_we_teach3_de',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='what_we_teach3_en',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='what_we_teach3_ro',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='what_we_teach4_de',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='what_we_teach4_en',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='what_we_teach4_ro',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
