# Generated by Django 3.2.18 on 2023-04-30 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0034_auto_20230430_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='counter1',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='about',
            name='counter2',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='about',
            name='counter3',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='about',
            name='counter4',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='about',
            name='counter_fact1',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='about',
            name='counter_fact1_de',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='counter_fact1_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='counter_fact1_ro',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='counter_fact2',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='about',
            name='counter_fact2_de',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='counter_fact2_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='counter_fact2_ro',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='counter_fact3',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='about',
            name='counter_fact3_de',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='counter_fact3_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='counter_fact3_ro',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='counter_fact4',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='about',
            name='counter_fact4_de',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='counter_fact4_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='counter_fact4_ro',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
