# Generated by Django 3.2.18 on 2023-04-30 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0035_auto_20230430_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='main_text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='about',
            name='main_text_de',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='main_text_en',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='main_text_ro',
            field=models.TextField(null=True),
        ),
    ]
