# Generated by Django 3.2.18 on 2023-04-30 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0037_auto_20230430_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='emphasize_what_we_teach1',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='about',
            name='emphasize_what_we_teach1_de',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='emphasize_what_we_teach1_en',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='emphasize_what_we_teach1_ro',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='emphasize_what_we_teach2',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='about',
            name='emphasize_what_we_teach2_de',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='emphasize_what_we_teach2_en',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='emphasize_what_we_teach2_ro',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='emphasize_what_we_teach3',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='about',
            name='emphasize_what_we_teach3_de',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='emphasize_what_we_teach3_en',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='emphasize_what_we_teach3_ro',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='emphasize_what_we_teach4',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='about',
            name='emphasize_what_we_teach4_de',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='emphasize_what_we_teach4_en',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='emphasize_what_we_teach4_ro',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
