# Generated by Django 3.2.18 on 2023-04-30 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0038_auto_20230430_1440'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='counter4',
        ),
        migrations.RemoveField(
            model_name='about',
            name='counter_fact4',
        ),
        migrations.RemoveField(
            model_name='about',
            name='counter_fact4_de',
        ),
        migrations.RemoveField(
            model_name='about',
            name='counter_fact4_en',
        ),
        migrations.RemoveField(
            model_name='about',
            name='counter_fact4_ro',
        ),
    ]
