# Generated by Django 3.2.18 on 2023-04-30 16:10

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0039_auto_20230430_1504'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=100)),
                ('main_explanation', models.TextField()),
                ('subtitle', models.CharField(blank=True, max_length=30)),
                ('second_text', models.TextField(blank=True, null=True)),
                ('image1', django_resized.forms.ResizedImageField(crop=None, force_format='WebP', keep_meta=True, quality=75, scale=0.5, size=[640, None], upload_to='faq_images')),
                ('image2', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WebP', keep_meta=True, quality=75, scale=0.5, size=[640, None], upload_to='faq_images')),
                ('image3', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WebP', keep_meta=True, quality=75, scale=0.5, size=[640, None], upload_to='faq_images')),
                ('image4', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WebP', keep_meta=True, quality=75, scale=0.5, size=[640, None], upload_to='faq_images')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=100)),
            ],
        ),
    ]
