# Generated by Django 3.2.18 on 2023-04-30 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0040_faq'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='main_explanation_de',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='main_explanation_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='main_explanation_ro',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_de',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_ro',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='second_text_de',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='second_text_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='second_text_ro',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='subtitle_de',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='subtitle_en',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='subtitle_ro',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
