# Generated by Django 3.2.18 on 2023-04-30 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0041_auto_20230430_1611'),
    ]

    operations = [
        migrations.RenameField(
            model_name='training',
            old_name='text',
            new_name='first_text',
        ),
        migrations.RenameField(
            model_name='training',
            old_name='text_de',
            new_name='first_text_de',
        ),
        migrations.RenameField(
            model_name='training',
            old_name='text_en',
            new_name='first_text_en',
        ),
        migrations.RenameField(
            model_name='training',
            old_name='text_ro',
            new_name='first_text_ro',
        ),
        migrations.AddField(
            model_name='training',
            name='second_text',
            field=models.TextField(default='a'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='training',
            name='second_text_de',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='training',
            name='second_text_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='training',
            name='second_text_ro',
            field=models.TextField(null=True),
        ),
    ]
